#!/bin/bash
#Author: Pierce Stegman
if [ -z "$1" ]; then
	echo "Usage: $0 [filename]"
	exit
fi
(convert "$1" -set colorspace Gray -separate -average -brightness-contrast -10x10 "fixed-$1") || echo "ERROR occured while fixing $1"
